### ISSUE TITLE
segfault with fastq

### ISSUE THREAD

**Issue by brentp** [splatlab/squeakr#15]
run as: `./squeakr-count 1 20 4 u.fq.gz` with the u.fq.gz attached here.
[u.fq.gz](https://github.com/splatlab/squeakr/files/1413116/u.fq.gz)

I get the backtrace:

```
(gdb) bt
#0  0x0000000000412d47 in shift_remainders (qf=0x7ffcfc33a1d0, start_index=65127, empty_index=294479)
    at threadsafe-gqf/gqf.c:720
#1  0x00000000004147b2 in insert1(QF *, __int128 unsigned, bool, bool) (qf=0x7ffcfc33a1d0, hash=14624935, lock=true, 
    spin=true) at threadsafe-gqf/gqf.c:1368
#2  0x0000000000415d89 in qf_insert (qf=0x7ffcfc33a1d0, key=14624935, value=0, count=1, lock=true, spin=true)
    at threadsafe-gqf/gqf.c:1822
#3  0x0000000000407bd4 in dump_local_qf_to_main (obj=0x2034c30) at main.cc:231
#4  0x0000000000408305 in reads_to_kmers (c=..., obj=0x2034c30) at main.cc:336
#5  0x00000000004085b2 in fastq_to_uint64kmers_prod (obj=0x2034c30) at main.cc:371
#6  0x0000000000411941 in boost::_bi::list1<boost::_bi::value<flush_object*> >::operator()<bool (*)(flush_object*), boost::_bi::list0> (this=0x2034e30, f=@0x2034e28: 0x408485 <fastq_to_uint64kmers_prod(flush_object*)>, a=...)
    at /usr/include/boost/bind/bind.hpp:253
#7  0x0000000000411594 in boost::_bi::bind_t<void, bool (*)(flush_object*), boost::_bi::list1<boost::_bi::value<flush_object*> > >::operator() (this=0x2034e28) at /usr/include/boost/bind/bind.hpp:893
#8  0x00000000004110be in boost::detail::thread_data<boost::_bi::bind_t<void, bool (*)(flush_object*), boost::_bi::list1<boost::_bi::value<flush_object*> > > >::run (this=0x2034c70) at /usr/include/boost/thread/detail/thread.hpp:116
#9  0x00007fc449e3d5d5 in ?? ()
#10 0x0000000000000000 in ?? ()
```

**Comment by prashantpandey** [comment]
Hi Brent,

There are more distinct k-mers in the dataset than 2^20 which the capacity of the data structure. 
I downloaded your fastq.gz file and ran it and there are ~3.5M distinct k-mers. So, you need to increase the second argument from 20 to 22. And it works.

'./squeakr-count 1 22 1 ~/Downloads/u.fq.gz'

Let me know if this fixes the issue.

Thanks,
Prashant

**Comment by brentp** [comment]
ok. that works. sorry for the noise. 

I guess you must have a different k-mer size than master as I get ~5.36M distint k-mers?
